import type {
  User, Challenge, Project, University, Organization,
  ImpactMetrics, Notification, Milestone, Task, Message,
  Partnership, Solution, Certificate, AIAnalysis,
  JharkhandDistrict, UserRole
} from '../../types';

// ─── Jharkhand Districts ────────────────────────────────────────────────────
export const JHARKHAND_DISTRICTS: JharkhandDistrict[] = [
  { id: 'ranchi', name: 'Ranchi', lat: 23.3441, lng: 85.3096, population: 1072731, challenges: 12, projects: 5, solutions: 3, citizens: 8400 },
  { id: 'dhanbad', name: 'Dhanbad', lat: 23.7957, lng: 86.4304, population: 2684487, challenges: 9, projects: 4, solutions: 2, citizens: 6200 },
  { id: 'jamshedpur', name: 'Jamshedpur', lat: 22.8046, lng: 86.2029, population: 1337131, challenges: 7, projects: 3, solutions: 2, citizens: 5100 },
  { id: 'bokaro', name: 'Bokaro', lat: 23.6693, lng: 86.1511, population: 2062330, challenges: 6, projects: 2, solutions: 1, citizens: 3800 },
  { id: 'deoghar', name: 'Deoghar', lat: 24.4855, lng: 86.6945, population: 1491879, challenges: 8, projects: 2, solutions: 1, citizens: 4200 },
  { id: 'dumka', name: 'Dumka', lat: 24.2668, lng: 87.2491, population: 1321442, challenges: 10, projects: 3, solutions: 2, citizens: 5900 },
  { id: 'hazaribagh', name: 'Hazaribagh', lat: 23.9925, lng: 85.3637, population: 1734005, challenges: 5, projects: 2, solutions: 1, citizens: 3100 },
  { id: 'giridih', name: 'Giridih', lat: 24.1884, lng: 86.3003, population: 2445203, challenges: 7, projects: 2, solutions: 1, citizens: 4700 },
  { id: 'ramgarh', name: 'Ramgarh', lat: 23.6298, lng: 85.5122, population: 949443, challenges: 4, projects: 1, solutions: 1, citizens: 2300 },
  { id: 'palamu', name: 'Palamu', lat: 24.0292, lng: 84.0634, population: 1939869, challenges: 11, projects: 3, solutions: 2, citizens: 7800 },
  { id: 'latehar', name: 'Latehar', lat: 23.7453, lng: 84.5024, population: 726978, challenges: 6, projects: 2, solutions: 1, citizens: 3400 },
  { id: 'gumla', name: 'Gumla', lat: 23.0453, lng: 84.5374, population: 1025656, challenges: 8, projects: 2, solutions: 1, citizens: 4100 },
  { id: 'simdega', name: 'Simdega', lat: 22.6153, lng: 84.5022, population: 599813, challenges: 5, projects: 1, solutions: 1, citizens: 2800 },
  { id: 'khunti', name: 'Khunti', lat: 23.0723, lng: 85.2763, population: 531885, challenges: 4, projects: 1, solutions: 0, citizens: 1900 },
  { id: 'chaibasa', name: 'Chaibasa', lat: 22.5588, lng: 85.8087, population: 1500000, challenges: 6, projects: 2, solutions: 1, citizens: 3600 },
];

// ─── Demo Users ─────────────────────────────────────────────────────────────
export const DEMO_USERS: Record<UserRole, User> = {
  citizen: {
    id: 'demo-citizen-1',
    email: 'rahul.mahto@demo.jhinnovate.in',
    displayName: 'Rahul Mahto',
    role: 'citizen',
    district: 'Dumka',
    phone: '+91 94310 00001',
    bio: 'Farmer from Dumka who cares about his community.',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  government: {
    id: 'demo-govt-1',
    email: 'collector.dumka@jharkhand.gov.in',
    displayName: 'Dr. Priya Singh (IAS)',
    role: 'government',
    organizationId: 'govt-jharkhand',
    district: 'Ranchi',
    bio: 'District Collector, Dumka — Championing innovation for Jharkhand.',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  university: {
    id: 'demo-univ-admin-1',
    email: 'vc@birsa.ac.in',
    displayName: 'Prof. Arun Kumar (VC)',
    role: 'university',
    universityId: 'univ-birsa',
    bio: 'Vice Chancellor, Birsa Institute of Technology — Fostering industry-academia collaboration.',
    createdAt: '2026-01-12T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  faculty: {
    id: 'demo-faculty-1',
    email: 'drverma@birsa.ac.in',
    displayName: 'Dr. Anita Verma',
    role: 'faculty',
    universityId: 'univ-birsa',
    department: 'Computer Science & Engineering',
    bio: 'Associate Professor | IoT, AI/ML, Water Quality Systems | 12 years research experience',
    skills: ['IoT', 'AI/ML', 'Python', 'Water Quality Systems', 'Research Methodology'],
    innovationPoints: 2840,
    badges: ['Research Champion', 'Industry Connector', 'Innovation Leader'],
    createdAt: '2026-01-14T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  student: {
    id: 'demo-student-1',
    email: 'amit.oraon@student.birsa.ac.in',
    displayName: 'Amit Oraon',
    role: 'student',
    universityId: 'univ-birsa',
    department: 'Computer Science & Engineering',
    bio: 'B.Tech CSE Final Year | Flutter + IoT Developer | Passionate about rural tech solutions',
    skills: ['Flutter', 'Python', 'IoT', 'Firebase', 'AI/ML'],
    innovationPoints: 1560,
    badges: ['Problem Solver', 'Prototype Builder', 'Community Champion'],
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  industry: {
    id: 'demo-industry-1',
    email: 'partnerships@demotech.in',
    displayName: 'Vikram Tiwari (DemoTech Solutions)',
    role: 'industry',
    organizationId: 'org-demotech',
    bio: 'Head of Corporate Innovation — DemoTech Solutions [DEMO ORGANIZATION]',
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  startup: {
    id: 'demo-startup-1',
    email: 'founder@agritech-demo.in',
    displayName: 'Sunita Munda (AgriTech Demo)',
    role: 'startup',
    organizationId: 'org-agritech-demo',
    bio: 'Founder, AgriTech Demo Startup — Rural IoT solutions [DEMO ORGANIZATION]',
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  admin: {
    id: 'demo-admin-1',
    email: 'admin@jhinnovate.in',
    displayName: 'Admin User',
    role: 'admin',
    bio: 'System Administrator — Jharkhand Innovation Hub',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
};

// ─── Demo Universities ───────────────────────────────────────────────────────
export const DEMO_UNIVERSITIES: University[] = [
  {
    id: 'univ-birsa',
    name: 'Birsa Institute of Technology',
    shortName: 'BIT Sindri',
    district: 'Dhanbad',
    type: 'state',
    departments: ['CSE', 'ECE', 'Mechanical', 'Civil', 'Chemical', 'Mining', 'Environmental Engg'],
    activeProjects: 8,
    totalStudents: 2800,
    ranking: 1,
    isDemo: true,
  },
  {
    id: 'univ-nitrr',
    name: 'NIT Jamshedpur',
    shortName: 'NIT JSR',
    district: 'Jamshedpur',
    type: 'nit',
    departments: ['CSE', 'ECE', 'Metallurgy', 'Production', 'Civil', 'Mechanical', 'Physics', 'Chemistry'],
    activeProjects: 6,
    totalStudents: 4200,
    ranking: 2,
    isDemo: true,
  },
  {
    id: 'univ-ru',
    name: 'Ranchi University',
    shortName: 'RU Ranchi',
    district: 'Ranchi',
    type: 'state',
    departments: ['Agriculture', 'Environmental Science', 'Botany', 'Zoology', 'Commerce', 'Law'],
    activeProjects: 4,
    totalStudents: 18000,
    ranking: 3,
    isDemo: true,
  },
  {
    id: 'univ-sidho',
    name: 'Sido Kanhu Murmu University',
    shortName: 'SKMU Dumka',
    district: 'Dumka',
    type: 'state',
    departments: ['Agriculture', 'Rural Development', 'Education', 'Arts', 'Science', 'Commerce'],
    activeProjects: 3,
    totalStudents: 12000,
    ranking: 4,
    isDemo: true,
  },
  {
    id: 'univ-xlri',
    name: 'Xavier School of Management',
    shortName: 'XLRI Jamshedpur',
    district: 'Jamshedpur',
    type: 'deemed',
    departments: ['Business Management', 'Human Resources', 'General Management', 'Social Work'],
    activeProjects: 2,
    totalStudents: 1200,
    ranking: 5,
    isDemo: true,
  },
];

// ─── Demo Challenges ─────────────────────────────────────────────────────────
export const DEMO_CHALLENGES: Challenge[] = [
  {
    id: 'ch-001',
    title: 'Unsafe Drinking Water in Rural Villages of Dumka',
    description: 'Multiple villages in Dumka district face severe drinking water contamination issues. Water sources show high fluoride, arsenic and iron content. Children and elderly are particularly affected with waterborne diseases. Current hand pumps are inadequate and lack quality monitoring.',
    category: 'Water Management',
    subcategory: 'Drinking Water Quality',
    district: 'Dumka',
    village: 'Sikaripara Panchayat',
    location: { lat: 24.2668, lng: 87.2491, address: 'Sikaripara Panchayat, Dumka, Jharkhand' },
    peopleAffected: 2400,
    urgency: 'high',
    currentSituation: 'Villages depend on contaminated hand pumps. No water treatment. Fluorosis cases increasing.',
    expectedImprovement: 'Real-time water quality monitoring with IoT sensors and AI-driven alerts for safe drinking water.',
    status: 'pilot',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    aiAnalysisId: 'ai-001',
    priority: 'high',
    aiScore: 8.7,
    validatedAt: '2026-02-20T09:00:00Z',
    validatedBy: 'demo-govt-1',
    assignedUniversityId: 'univ-birsa',
    projectId: 'proj-001',
    submittedAt: '2026-02-15T10:30:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-002',
    title: 'Lack of Digital Literacy in Tribal Schools',
    description: 'Tribal schools in Khunti and Gumla districts have no functional computers or digital infrastructure. Students miss out on digital education which hampers their future opportunities.',
    category: 'Education',
    subcategory: 'Digital Literacy',
    district: 'Khunti',
    village: 'Torpa Block',
    location: { lat: 23.0723, lng: 85.2763 },
    peopleAffected: 3800,
    urgency: 'medium',
    status: 'project_created',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'medium',
    aiScore: 7.2,
    validatedAt: '2026-03-10T09:00:00Z',
    assignedUniversityId: 'univ-ru',
    projectId: 'proj-002',
    submittedAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-08-01T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-003',
    title: 'Crop Disease Identification for Paddy Farmers',
    description: 'Paddy farmers in Palamu cannot identify crop diseases early, leading to 30-40% yield loss annually. No expert guidance available in villages. Farmers need affordable, mobile-based crop disease detection.',
    category: 'Agriculture',
    subcategory: 'Crop Disease Management',
    district: 'Palamu',
    village: 'Chainpur Block',
    location: { lat: 24.0292, lng: 84.0634 },
    peopleAffected: 5600,
    urgency: 'high',
    status: 'validated',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'high',
    aiScore: 8.1,
    validatedAt: '2026-04-01T09:00:00Z',
    submittedAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-07-15T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-004',
    title: 'Solid Waste Mismanagement in Hazaribagh Town',
    description: 'Hazaribagh town generates 85 tonnes of solid waste daily. Poor waste segregation, no composting, and inadequate collection routes lead to open dumping and environmental hazard near Hazaribagh Lake.',
    category: 'Environment',
    subcategory: 'Solid Waste Management',
    district: 'Hazaribagh',
    location: { lat: 23.9925, lng: 85.3637 },
    peopleAffected: 9800,
    urgency: 'high',
    status: 'government_review',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'high',
    aiScore: 7.9,
    submittedAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-06-01T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-005',
    title: 'No Maternal Health Monitoring in Remote Villages',
    description: 'Remote villages in Simdega and Latehar districts have no antenatal care monitoring. High maternal mortality due to delayed diagnosis and lack of ASHA worker digital tools.',
    category: 'Healthcare',
    subcategory: 'Maternal Health',
    district: 'Simdega',
    location: { lat: 22.6153, lng: 84.5022 },
    peopleAffected: 1800,
    urgency: 'critical',
    status: 'university_matched',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'critical',
    aiScore: 9.2,
    validatedAt: '2026-04-20T09:00:00Z',
    assignedUniversityId: 'univ-nitrr',
    submittedAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-05-10T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-006',
    title: 'Illegal Coal Mining Causing Land Subsidence in Dhanbad',
    description: 'Illegal coal mining in Jharia (Dhanbad) has caused underground fires and severe land subsidence. Thousands displaced. Underground fire has been burning for 100+ years.',
    category: 'Environment',
    subcategory: 'Mining & Land Safety',
    district: 'Dhanbad',
    location: { lat: 23.7957, lng: 86.4304 },
    peopleAffected: 25000,
    urgency: 'critical',
    status: 'submitted',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'critical',
    aiScore: 9.5,
    submittedAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-007',
    title: 'Road Connectivity Issues in Tribal Belt',
    description: 'Tribal villages in Gumla and Simdega lack all-weather road connectivity. During monsoon, villages become isolated for months, cutting off medical, food and education access.',
    category: 'Urban Development',
    subcategory: 'Rural Road Connectivity',
    district: 'Gumla',
    location: { lat: 23.0453, lng: 84.5374 },
    peopleAffected: 12000,
    urgency: 'high',
    status: 'ai_analyzed',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'high',
    aiScore: 7.5,
    submittedAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-06-21T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'ch-008',
    title: 'Solar Energy Access for Off-Grid Villages',
    description: 'Over 200 villages in Latehar district have no electricity access. Solar microgrids could be a sustainable solution but there is no awareness, financing or technical support.',
    category: 'Energy',
    subcategory: 'Renewable Energy Access',
    district: 'Latehar',
    location: { lat: 23.7453, lng: 84.5024 },
    peopleAffected: 8400,
    urgency: 'high',
    status: 'project_created',
    citizenId: 'demo-citizen-1',
    citizenName: 'Rahul Mahto',
    priority: 'high',
    aiScore: 8.3,
    validatedAt: '2026-03-15T09:00:00Z',
    assignedUniversityId: 'univ-nitrr',
    projectId: 'proj-003',
    submittedAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-07-01T07:00:00Z',
    isDemo: true,
  },
];

// ─── Demo Projects ───────────────────────────────────────────────────────────
export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    title: 'AI + IoT Water Quality Monitoring System',
    challengeId: 'ch-001',
    universityId: 'univ-birsa',
    facultyId: 'demo-faculty-1',
    status: 'pilot',
    progress: 78,
    health: 'good',
    risk: 'low',
    delayProbability: 12,
    collaborationScore: 91,
    impactPotential: 'very_high',
    description: 'Real-time IoT sensor network with AI-powered anomaly detection for drinking water quality monitoring in rural Jharkhand. Flutter app for ASHA workers and government dashboard for district officials.',
    objectives: [
      'Deploy 15 IoT water quality sensors across Sikaripara Panchayat',
      'Build AI model for contamination prediction',
      'Create Flutter mobile app for citizens and ASHA workers',
      'Integrate government dashboard for district monitoring',
      'Train 40 community members on system usage',
    ],
    timeline: { startDate: '2026-03-01', expectedEndDate: '2026-11-30' },
    budget: { estimated: 850000, allocated: 800000, spent: 524000, currency: 'INR' },
    location: 'Sikaripara Panchayat, Dumka',
    district: 'Dumka',
    tags: ['IoT', 'AI/ML', 'Flutter', 'Water Quality', 'Rural'],
    aiRecommendation: 'Based on current progress (78%) and team velocity, begin pilot testing phase. Consider involving 2 more IoT engineers for sensor deployment.',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-09-11T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'proj-002',
    title: 'Digital Learning Labs for Tribal Schools',
    challengeId: 'ch-002',
    universityId: 'univ-ru',
    facultyId: 'demo-faculty-1',
    status: 'active',
    progress: 45,
    health: 'fair',
    risk: 'medium',
    delayProbability: 28,
    collaborationScore: 72,
    impactPotential: 'high',
    description: 'Setting up solar-powered digital learning labs with offline e-content in tribal schools across Khunti district. Raspberry Pi-based thin client setup with locally-cached educational content.',
    objectives: [
      'Install 5 digital learning labs in tribal schools',
      'Develop offline educational content in tribal languages',
      'Train 25 teachers on digital teaching methods',
      'Create student progress tracking system',
    ],
    timeline: { startDate: '2026-04-01', expectedEndDate: '2026-12-31' },
    budget: { estimated: 600000, allocated: 550000, spent: 187000, currency: 'INR' },
    district: 'Khunti',
    tags: ['Education', 'Digital', 'Tribal', 'Raspberry Pi'],
    createdAt: '2026-04-01T09:00:00Z',
    updatedAt: '2026-09-01T07:00:00Z',
    isDemo: true,
  },
  {
    id: 'proj-003',
    title: 'Solar Microgrid for Off-Grid Villages',
    challengeId: 'ch-008',
    universityId: 'univ-nitrr',
    facultyId: 'demo-faculty-1',
    status: 'prototype',
    progress: 35,
    health: 'good',
    risk: 'low',
    delayProbability: 18,
    collaborationScore: 85,
    impactPotential: 'high',
    description: 'Community-owned solar microgrid model for 10 off-grid villages in Latehar. Smart load management with IoT-based monitoring and mobile payment integration for energy billing.',
    objectives: [
      'Design 10 kW microgrid prototype',
      'Build smart metering system',
      'Create mobile payment app for energy billing',
      'Train village energy committees',
    ],
    timeline: { startDate: '2026-05-01', expectedEndDate: '2027-03-31' },
    budget: { estimated: 1200000, allocated: 1000000, spent: 312000, currency: 'INR' },
    district: 'Latehar',
    tags: ['Solar', 'IoT', 'Energy', 'Rural', 'Microgrid'],
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-08-15T07:00:00Z',
    isDemo: true,
  },
];

// ─── Demo AI Analysis ────────────────────────────────────────────────────────
export const DEMO_AI_ANALYSIS: AIAnalysis = {
  id: 'ai-001',
  challengeId: 'ch-001',
  category: 'Water Management',
  subcategory: 'Drinking Water Quality',
  priority: 'high',
  severityScore: 8.7,
  estimatedPeopleAffected: 2400,
  requiredSkills: ['IoT', 'Flutter', 'AI/ML', 'Data Analytics', 'Water Quality Engineering', 'Firebase', 'Python'],
  recommendedSolution: 'AI + IoT Water Quality Monitoring System with real-time contamination alerts and citizen mobile app',
  solutionType: 'Technology + Community',
  keywords: ['water', 'contamination', 'fluoride', 'arsenic', 'rural', 'drinking water', 'handpump'],
  confidence: 94,
  duplicates: [
    { challengeId: 'ch-sim-1', title: 'Water Contamination in Pakur Block', similarity: 87, district: 'Pakur', status: 'validated' },
    { challengeId: 'ch-sim-2', title: 'Fluoride in Groundwater — Giridih', similarity: 81, district: 'Giridih', status: 'project_created' },
  ],
  universityMatches: [
    { universityId: 'univ-birsa', universityName: 'BIT Sindri', matchScore: 96, reasons: ['Strong IoT Lab', 'Environmental Engineering dept', 'Proximity to Dumka', 'Prior water projects'], departments: ['CSE', 'Environmental Engg', 'Chemical'] },
    { universityId: 'univ-nitrr', universityName: 'NIT Jamshedpur', matchScore: 89, reasons: ['Research excellence', 'Strong AI/ML faculty'], departments: ['CSE', 'Metallurgy'] },
  ],
  industryMatches: [
    { industryId: 'org-demotech', companyName: 'DemoTech Solutions [DEMO]', matchScore: 94, reasons: ['IoT hardware expertise', 'Water technology portfolio', 'Rural deployment experience', 'Pilot infrastructure'], supportTypes: ['Hardware', 'Mentorship', 'Pilot Support'] },
  ],
  impactPrediction: {
    reach: 2400,
    timeToSolve: '8-12 months',
    costEstimate: '₹8-12 Lakhs',
    sdgGoals: ['SDG 6 — Clean Water', 'SDG 3 — Good Health', 'SDG 11 — Sustainable Communities'],
  },
  processedAt: '2026-02-15T10:45:00Z',
  engine: 'local',
  isDemo: true,
};

// ─── Demo Milestones ─────────────────────────────────────────────────────────
export const DEMO_MILESTONES: Milestone[] = [
  { id: 'ms-001', projectId: 'proj-001', title: 'Research & Requirements', description: 'Stakeholder interviews, water sample analysis, sensor selection', progress: 100, targetDate: '2026-04-30', completedAt: '2026-04-25T09:00:00Z', status: 'completed', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-04-25T09:00:00Z' },
  { id: 'ms-002', projectId: 'proj-001', title: 'IoT Sensor Prototype', description: 'Design and build first IoT sensor with pH, TDS, fluoride sensors', progress: 100, targetDate: '2026-06-15', completedAt: '2026-06-10T09:00:00Z', status: 'completed', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-06-10T09:00:00Z' },
  { id: 'ms-003', projectId: 'proj-001', title: 'AI Model Development', description: 'Train contamination prediction model on Jharkhand groundwater data', progress: 85, targetDate: '2026-08-31', status: 'in_progress', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-09-01T09:00:00Z' },
  { id: 'ms-004', projectId: 'proj-001', title: 'Flutter App & Dashboard', description: 'Citizen app, ASHA worker app, and government monitoring dashboard', progress: 70, targetDate: '2026-09-30', status: 'in_progress', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-09-05T09:00:00Z' },
  { id: 'ms-005', projectId: 'proj-001', title: 'Field Deployment — Pilot', description: 'Install 15 sensors across 5 villages, train 40 community members', progress: 40, targetDate: '2026-10-31', status: 'in_progress', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-09-10T09:00:00Z' },
  { id: 'ms-006', projectId: 'proj-001', title: 'Impact Assessment & Scale', description: 'Measure impact, document learnings, prepare scale-up plan', progress: 0, targetDate: '2026-11-30', status: 'pending', createdById: 'demo-faculty-1', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-03-01T09:00:00Z' },
];

// ─── Demo Tasks ──────────────────────────────────────────────────────────────
export const DEMO_TASKS: Task[] = [
  { id: 'task-001', projectId: 'proj-001', title: 'Deploy IoT sensors in Sector A villages', description: 'Install 5 sensors with solar-powered ESP32 units in villages 1-5', status: 'in_progress', priority: 'high', assigneeId: 'demo-student-1', assigneeName: 'Amit Oraon', createdById: 'demo-faculty-1', dueDate: '2026-09-20', order: 1, createdAt: '2026-09-01T09:00:00Z', updatedAt: '2026-09-10T09:00:00Z' },
  { id: 'task-002', projectId: 'proj-001', title: 'Complete AI anomaly detection module', description: 'Finalize LSTM model for real-time water quality anomaly detection', status: 'in_progress', priority: 'high', assigneeId: 'demo-student-1', assigneeName: 'Amit Oraon', createdById: 'demo-faculty-1', dueDate: '2026-09-25', order: 2, createdAt: '2026-09-01T09:00:00Z', updatedAt: '2026-09-08T09:00:00Z' },
  { id: 'task-003', projectId: 'proj-001', title: 'Finalize Flutter citizen notification system', description: 'Build push notification system for contamination alerts in Flutter app', status: 'review', priority: 'medium', assigneeId: 'demo-student-1', assigneeName: 'Amit Oraon', createdById: 'demo-faculty-1', dueDate: '2026-09-18', order: 3, createdAt: '2026-09-01T09:00:00Z', updatedAt: '2026-09-11T07:00:00Z' },
  { id: 'task-004', projectId: 'proj-001', title: 'Government dashboard testing', description: 'UAT with Dumka district office staff', status: 'todo', priority: 'medium', assigneeId: 'demo-student-1', assigneeName: 'Amit Oraon', createdById: 'demo-faculty-1', dueDate: '2026-10-05', order: 4, createdAt: '2026-09-01T09:00:00Z', updatedAt: '2026-09-01T09:00:00Z' },
  { id: 'task-005', projectId: 'proj-001', title: 'Community training materials', description: 'Create video + pamphlet training content in local language (Santhali/Hindi)', status: 'todo', priority: 'low', createdById: 'demo-faculty-1', dueDate: '2026-10-15', order: 5, createdAt: '2026-09-01T09:00:00Z', updatedAt: '2026-09-01T09:00:00Z' },
  { id: 'task-006', projectId: 'proj-001', title: 'Integrate DemoTech IoT hardware APIs', description: 'Connect DemoTech Solutions sensor firmware API with our backend', status: 'completed', priority: 'high', assigneeId: 'demo-student-1', assigneeName: 'Amit Oraon', createdById: 'demo-faculty-1', completedAt: '2026-08-28T09:00:00Z', order: 6, createdAt: '2026-08-01T09:00:00Z', updatedAt: '2026-08-28T09:00:00Z' },
];

// ─── Demo Messages ───────────────────────────────────────────────────────────
export const DEMO_MESSAGES: Message[] = [
  { id: 'msg-001', projectId: 'proj-001', senderId: 'demo-faculty-1', senderName: 'Dr. Anita Verma', senderRole: 'faculty', text: 'Team — great progress this week! The IoT prototype is looking excellent. Let\'s focus on completing the AI model by September 25.', createdAt: '2026-09-10T09:30:00Z' },
  { id: 'msg-002', projectId: 'proj-001', senderId: 'demo-student-1', senderName: 'Amit Oraon', senderRole: 'student', text: 'The Flutter notification system is ready for review. I\'ve tested with 3 different contamination scenarios. Pushing the PR now.', createdAt: '2026-09-10T11:15:00Z' },
  { id: 'msg-003', projectId: 'proj-001', senderId: 'demo-industry-1', senderName: 'Vikram Tiwari', senderRole: 'industry', text: 'The IoT hardware samples from DemoTech are arriving next Monday. We\'ll also send 2 engineers to assist with deployment in Sector A.', createdAt: '2026-09-10T14:00:00Z' },
  { id: 'msg-004', projectId: 'proj-001', senderId: 'system', senderName: 'System', senderRole: 'admin', text: '🎯 Milestone "IoT Sensor Prototype" marked as COMPLETED by Dr. Anita Verma', isSystem: true, createdAt: '2026-09-09T09:00:00Z' },
  { id: 'msg-005', projectId: 'proj-001', senderId: 'demo-govt-1', senderName: 'Dr. Priya Singh (IAS)', senderRole: 'government', text: 'Visited the pilot site last week. The water quality improvement is already visible. District administration will extend this to 10 more panchayats after pilot success.', createdAt: '2026-09-08T16:30:00Z' },
];

// ─── Demo Notifications ──────────────────────────────────────────────────────
export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: 'notif-001', userId: 'demo-citizen-1', type: 'impact_updated', title: '2,400 People Now Benefited!', body: 'Your reported problem "Unsafe Drinking Water" has reached pilot stage. 2,400 people in Dumka district are now benefiting from clean water monitoring.', link: '/citizen/challenges/ch-001', isRead: false, createdAt: '2026-09-10T09:00:00Z' },
  { id: 'notif-002', userId: 'demo-citizen-1', type: 'pilot_started', title: 'Pilot Testing Started!', body: 'The IoT Water Quality Monitoring project has entered pilot testing phase in your district.', link: '/citizen/challenges/ch-001', isRead: false, createdAt: '2026-09-05T10:00:00Z' },
  { id: 'notif-003', userId: 'demo-citizen-1', type: 'ai_analysis_completed', title: 'AI Analysis Complete', body: 'Your reported challenge has been analyzed. AI Priority: HIGH (8.7/10). Category: Water Management.', isRead: true, createdAt: '2026-02-15T11:00:00Z' },
  { id: 'notif-004', userId: 'demo-student-1', type: 'student_invited', title: 'Project Invitation!', body: 'Dr. Anita Verma has invited you to join the Water Quality Monitoring project team as IoT Developer.', link: '/app/projects/proj-001', isRead: false, createdAt: '2026-09-11T07:00:00Z' },
  { id: 'notif-005', userId: 'demo-govt-1', type: 'challenge_submitted', title: 'New Challenge — Immediate Review', body: '6 new challenges submitted this week. 2 marked HIGH priority. Immediate review required.', link: '/app/challenges', isRead: false, createdAt: '2026-09-11T06:00:00Z' },
];

// ─── Demo Impact Metrics ─────────────────────────────────────────────────────
export const DEMO_IMPACT: ImpactMetrics = {
  id: 'impact-001',
  projectId: 'proj-001',
  challengeId: 'ch-001',
  citizensImpacted: 2400,
  villagesImpacted: 5,
  jobsCreated: 12,
  costSavings: 480000,
  environmentScore: 78,
  sdgGoals: ['SDG 6', 'SDG 3', 'SDG 11'],
  measuredAt: '2026-09-10T09:00:00Z',
};

// ─── Industry Partners ───────────────────────────────────────────────────────
export const DEMO_INDUSTRY_PARTNERS: Organization[] = [
  { id: 'org-demotech', name: 'DemoTech Solutions [DEMO]', type: 'industry', district: 'Ranchi', description: 'IoT hardware and rural technology company. [DEMO — Fictional organization for demonstration purposes]', isDemo: true },
  { id: 'org-agritech-demo', name: 'AgriTech Demo Startup [DEMO]', type: 'startup', district: 'Jamshedpur', description: 'AgriTech startup focusing on AI-driven crop solutions. [DEMO — Fictional organization]', isDemo: true },
  { id: 'org-watercare-demo', name: 'WaterCare Systems [DEMO]', type: 'industry', district: 'Dhanbad', description: 'Water treatment and monitoring solutions. [DEMO — Fictional organization]', isDemo: true },
  { id: 'org-edu-demo', name: 'EduTech Rural [DEMO]', type: 'startup', district: 'Hazaribagh', description: 'Digital education for rural India. [DEMO — Fictional organization]', isDemo: true },
  { id: 'org-solar-demo', name: 'SolarGram [DEMO]', type: 'startup', district: 'Bokaro', description: 'Solar microgrid solutions for off-grid villages. [DEMO — Fictional organization]', isDemo: true },
];

// ─── Demo Categories ─────────────────────────────────────────────────────────
export const CHALLENGE_CATEGORIES = [
  { id: 'water', name: 'Water Management', icon: '💧', color: '#2563EB', count: 48 },
  { id: 'education', name: 'Education', icon: '📚', color: '#7C3AED', count: 42 },
  { id: 'agriculture', name: 'Agriculture', icon: '🌾', color: '#059669', count: 56 },
  { id: 'healthcare', name: 'Healthcare', icon: '🏥', color: '#DC2626', count: 38 },
  { id: 'environment', name: 'Environment', icon: '🌿', color: '#166534', count: 44 },
  { id: 'energy', name: 'Energy', icon: '⚡', color: '#F59E0B', count: 29 },
  { id: 'urban', name: 'Urban Development', icon: '🏙️', color: '#0EA5E9', count: 35 },
  { id: 'rural', name: 'Rural Livelihoods', icon: '🏘️', color: '#F97316', count: 51 },
  { id: 'accessibility', name: 'Accessibility', icon: '♿', color: '#8B5CF6', count: 18 },
  { id: 'admin', name: 'Public Administration', icon: '🏛️', color: '#6366F1', count: 22 },
];

// ─── Demo Statistics ─────────────────────────────────────────────────────────
export const DEMO_STATS = {
  challenges: 2548,
  activeProjects: 684,
  solutions: 187,
  citizensImpacted: 85000,
  universities: 10,
  students: 3200,
  faculty: 180,
  industryPartners: 54,
  villages: 342,
  jobsCreated: 1840,
  patents: 23,
  startups: 12,
};

// ─── Demo Certificate ────────────────────────────────────────────────────────
export const DEMO_CERTIFICATE: Certificate = {
  id: 'cert-001',
  studentId: 'demo-student-1',
  studentName: 'Amit Oraon',
  university: 'Birsa Institute of Technology',
  projectId: 'proj-001',
  projectTitle: 'AI + IoT Water Quality Monitoring System',
  projectRole: 'IoT Developer & AI Engineer',
  completedAt: '2026-11-30',
  impactSummary: '2,400 citizens benefited in Dumka district with real-time safe water monitoring',
  issueDate: '2026-12-15',
  isValid: true,
};

// ─── Student Matches ─────────────────────────────────────────────────────────
export const DEMO_STUDENT_MATCHES = [
  { studentId: 'demo-student-1', studentName: 'Amit Oraon', matchScore: 95, skills: ['Flutter', 'Python', 'IoT', 'Firebase'], role: 'IoT Developer & AI Engineer', university: 'BIT Sindri' },
  { studentId: 'demo-student-2', studentName: 'Priya Kumari', matchScore: 91, skills: ['AI/ML', 'Python', 'TensorFlow', 'Data Analytics'], role: 'AI/ML Engineer', university: 'NIT Jamshedpur' },
  { studentId: 'demo-student-3', studentName: 'Rohit Soren', matchScore: 86, skills: ['Flutter', 'Firebase', 'UI/UX', 'React'], role: 'Frontend Developer', university: 'BIT Sindri' },
  { studentId: 'demo-student-4', studentName: 'Anjali Tirkey', matchScore: 84, skills: ['Python', 'Data Science', 'IoT', 'Embedded'], role: 'Data Analyst', university: 'SKMU Dumka' },
  { studentId: 'demo-student-5', studentName: 'Sanjay Munda', matchScore: 82, skills: ['Project Management', 'Research', 'Documentation'], role: 'Research Lead', university: 'Ranchi University' },
];

// ─── Guided Demo Journey Stages ──────────────────────────────────────────────
export const DEMO_JOURNEY_STAGES = [
  { id: 'citizen', label: 'Citizen Reports', icon: '👤', color: '#166534', description: 'Rahul Mahto from Dumka reports unsafe drinking water affecting 2,400 villagers' },
  { id: 'ai', label: 'AI Analysis', icon: '🤖', color: '#2563EB', description: 'AI classifies as Water Management, assigns High Priority (8.7/10), detects 2 similar challenges' },
  { id: 'government', label: 'Government Validation', icon: '🏛️', color: '#7C3AED', description: 'District Collector Dr. Priya Singh validates and assigns to BIT Sindri' },
  { id: 'university', label: 'University Accepts', icon: '🎓', color: '#059669', description: 'BIT Sindri accepts challenge, assigns to CSE & Environmental Engineering departments' },
  { id: 'faculty', label: 'Faculty Creates Project', icon: '👩‍🏫', color: '#F97316', description: 'Dr. Anita Verma creates "AI + IoT Water Quality Monitoring" project and invites students' },
  { id: 'students', label: 'Students Join', icon: '👨‍💻', color: '#F59E0B', description: 'Amit Oraon and 7 other students join the project team based on AI matching (95% match)' },
  { id: 'industry', label: 'Industry Supports', icon: '🏭', color: '#DC2626', description: 'DemoTech Solutions provides IoT hardware, mentorship and pilot support' },
  { id: 'prototype', label: 'Prototype Built', icon: '🔧', color: '#0EA5E9', description: 'IoT sensor prototype completed with pH, TDS and fluoride measurement capability' },
  { id: 'pilot', label: 'Pilot Testing', icon: '🚀', color: '#8B5CF6', description: '15 sensors deployed across 5 villages with real-time monitoring dashboard live' },
  { id: 'deployment', label: 'Solution Deployed', icon: '📡', color: '#166534', description: 'Full deployment across Sikaripara Panchayat with 40 trained community members' },
  { id: 'impact', label: 'Impact Measured', icon: '🌟', color: '#059669', description: '2,400 citizens now have safe water access. Zero waterborne disease outbreaks reported.' },
];
